language: cpp
dist: focal

jobs:
  include:
    # app for android
    - language: android
      os: linux
      dist: bionic
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
      addons:
        apt:
          packages:
            - ant
            - oracle-java8-installer
            - oracle-java8-set-default
            - jq
            - gradle
            - nodejs
            - build-essential
            - lib32stdc++6
            - libstdc++6
            - libsecret-1-dev
            - lib32z1
            - gcc-4.8
            - g++-4.8
            - gcc-4.8-multilib
            - g++-4.8-multilib
      install:
        - cd grillee-app
        - nvm install 14
        - npm install ionic cordova
        - npm install
      script:
        - ionic cordova platform add android
        - ionic cordova build --release --prod android
      
      
    # firmware
    - language: cpp
      os: linux
      dist: focal
      script:
        - ./build_travis.sh
        - cd build

deploy:
  provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN  # set as env variable in the travis build settings page
  file_glob: true
  file:
    - grillee-*.zip
    - grillee-*.bin
  prerelease: true
  overwrite: true
  on:
    tags: true

