matrix:
  include:
    # app for android
    - language: android
      os: linux
      dist: trusty
      sudo: true
      android:
        components:
          - build-tools-28.0.3
          - android-28
      addons:
        apt:
          packages:
            - ant
            - oracle-java8-installer
            - oracle-java8-set-default
      install:
        - curl -sL https://deb.nodesource.com/setup_12.x | bash -
        - apt-get install nodejs
        - apt-get install build-essential
        - cd lotusble-app
        - npm install ionic cordova
        - npm install
      script:
        - ionic cordova platform add android
        - ionic cordova build --release --prod android
      
      
    # firmware
    - language: cpp
      os: linux
      dist: bionic
      script:
        - ./build_travis.sh
        - cd build

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN  # set as env variable in the travis build settings page
  file_glob: true
  file:
    - lotusble-*.zip
    - lotusble-*.bin
  keep_history: true
  prerelease: true
  overwrite: true
  on:
    tags: true

